@startuml AIServiceComponent
' AIServiceComponent.puml (가이드 준수)

package "Interface Layer" {
  interface IAIServiceApi
  interface INLPServiceApi

  component AIServiceApiImpl
  component NLPServiceApiImpl
  
  IAIServiceApi -- AIServiceApiImpl
  INLPServiceApi -- NLPServiceApiImpl
}

package "Business Layer" {
  interface IKeywordExtractionService
  interface IContentAnalysisService
  
  component LLMKeywordExtractor
  component ContentAnalyzer
  component QueryTokenizer
  component IndexUpdateProcessor
  
  ' Service implementations
  IKeywordExtractionService -- LLMKeywordExtractor
  IContentAnalysisService -- ContentAnalyzer
  
  ' Business layer internal relationships
  ContentAnalyzer ..( IKeywordExtractionService : <<use>>
  IndexUpdateProcessor ..( IContentAnalysisService : <<use>>
}

package "System Interface Layer" {
  interface IPanDokuModelService
  interface ISearchRepository
  interface IMessagePublisherService
  
  component PanDokuModelServiceAdapter
  component SearchRepositoryImpl
  component MessageBrokerComponent
  
  database SearchDatabase
  
  IPanDokuModelService -- PanDokuModelServiceAdapter
  ISearchRepository -- SearchRepositoryImpl
  IMessagePublisherService -- MessageBrokerComponent
  
  SearchRepositoryImpl ..( SearchDatabase : <<JDBC>>
}

' 패키지 외부 연결
' Interface Layer -> Business Layer
AIServiceApiImpl ..( IKeywordExtractionService : <<use>>
NLPServiceApiImpl ..( IContentAnalysisService : <<use>>

' Business Layer -> System Interface Layer
LLMKeywordExtractor ..( IPanDokuModelService : <<HTTP>>
ContentAnalyzer ..( ISearchRepository : <<query>>
ContentAnalyzer ..( IMessagePublisherService : <<publish>>
IndexUpdateProcessor ..( ISearchRepository : <<persist>>

@enduml
