@startuml BranchOwnerServiceComponent
' BranchOwnerServiceComponent.puml (가이드 준수)
' UC-03: 지점주 계정 등록, UC-18: 지점 정보 등록, UC-19: 고객 리뷰 조회

package "Interface Layer" {
  interface IBranchOwnerApi
  interface IBranchQueryApi

  component BranchOwnerController
  component BranchQueryController
  
  IBranchOwnerApi -- BranchOwnerController
  IBranchQueryApi -- BranchQueryController
}

package "Business Layer" {
  interface IBranchOwnerManagementService
  interface IBranchInfoService
  
  component BranchOwnerManager
  component BranchInfoValidator
  component BranchEventProcessor
  
  ' Service implementations
  IBranchOwnerManagementService -- BranchOwnerManager
  IBranchInfoService -- BranchInfoValidator
  
  ' Business layer internal relationships
  BranchOwnerManager ..( IBranchInfoService : <<use>>
  BranchEventProcessor ..( IBranchOwnerManagementService : <<use>>
}

package "System Interface Layer" {
  interface IBranchRepository
  interface IAuthRepository
  interface IMessagePublisherService
  interface IMessageSubscriptionService
  
  component BranchJpaRepository
  component AuthJpaRepository
  component RabbitMQAdapter
  
  database BranchDatabase
  database AuthDatabase
  
  IBranchRepository -- BranchJpaRepository
  IAuthRepository -- AuthJpaRepository
  IMessagePublisherService -- RabbitMQAdapter
  IMessageSubscriptionService -- RabbitMQAdapter
  
  BranchJpaRepository ..( BranchDatabase : <<JDBC>>
  AuthJpaRepository ..( AuthDatabase : <<JDBC>>
}

' 패키지 외부 연결
' Interface Layer -> Business Layer
BranchOwnerController ..( IBranchOwnerManagementService : <<HTTP>>
BranchQueryController ..( IBranchInfoService : <<HTTP>>

' Business Layer -> System Interface Layer
BranchOwnerManager ..( IBranchRepository : <<JDBC>>
BranchOwnerManager ..( IAuthRepository : <<JDBC>>
BranchOwnerManager ..( IMessagePublisherService : <<RabbitMQ>>
BranchInfoValidator ..( IBranchRepository : <<query>>
BranchEventProcessor ..( IBranchRepository : <<persist>>
BranchEventProcessor ..( IMessageSubscriptionService : <<subscribe>>

@enduml
